sonar.projectKey=wasimbaari_zoom-clone
sonar.organization=wasimbaari
sonar.sources=.
sonar.host.url=https://sonarcloud.io

# Exclude terraform and k8s from code analysis (we use checkov/trivy for those)
sonar.exclusions=terraform/**, k8s/**, node_modules/**, .next/**