apiVersion: v1
kind: Service
metadata:
  name: zoom-clone-service
  namespace: production
spec:
  selector:
    app: zoom-clone
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000 
  type: LoadBalancer